apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  namespace: default
  name: dd
spec:
  global:
    image: 8.0.0
  service:
    type: ClusterIP
  redisExporter:
    enabled: false
  mode: cluster
